### ISSUE TITLE
Error: Cannot find module './assets/empty-module.js'

### ISSUE THREAD

**Issue by fahrinh** [tj/node-prune#6]
I got a React Native project
This tool deleted a required file

```
$ npm start

> ZZZ@0.0.1 start /Users/fahri/Projects/ZZZ
> node node_modules/react-native/local-cli/cli.js start

module.js:471
    throw err;
    ^

Error: Cannot find module './assets/empty-module.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/Users/fahri/Projects/ZZZ/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:539:39)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/fahri/Projects/ZZZ/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ZZZ@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ZZZ@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fahri/.npm/_logs/2017-11-19T08_26_10_826Z-debug.log
```

**Comment by tuananh** [comment]
this problem is bound to happen. maybe introduce a config file like `.yarnclean`

**Comment by ajalger** [comment]
I think that's a yarn problem see: https://github.com/yarnpkg/yarn/issues/2206

**Comment by tmaly1980** [comment]
I ended up removing my .yarnclean file (which was way overgeneralized), removed node_modules, then ran yarn again. Seems to have been fixed. I don't recall calling yarn clean on my project, but it got to the point where once I added a new dependency, it just broke everything. All my graphical assets inside my node_modules were erased.

**Comment by chinanf-boy** [comment]
The `assets/`  will be `del`

https://github.com/tj/node-prune/blob/master/prune.go#L81
``` go
// DefaultDirectories pruned.
//
// Copied from yarn (mostly).
var DefaultDirectories = []string{
	"__tests__",
	"test",
	"tests",
	"powered-test",
	"docs",
	"doc",
	".idea",
	".vscode",
	"website",
	"images",
	"assets",
	"example",
	"examples",
	"coverage",
	".nyc_output",
	".circleci",
	".github",
}
```
